version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: analytics-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'aad1'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      # Bu satır, veritabanı yedeğini (init.sql) alıp ilk kurulumda otomatik çalıştırır
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Verilerin silinmemesi için kalıcı depolama alanı yaratır
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend/analytics-backend
    container_name: analytics-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/aad1
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - mysql-db

  frontend:
    build:
      context: ./frontend
    container_name: analytics-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql-data:
